[package]
name = "blob-bundle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bytes = "1.5"
crc32fast = "1.3"
thiserror = "2.0.16"
tokio.workspace = true
tracing.workspace = true
walrus-core.workspace = true

[dev-dependencies]
tempfile = "3.8"