[package]
name = "blob-bundle"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bytes = "1.5"
crc32fast = "1.3"
thiserror = "2.0.16"
walrus-core.workspace = true

[dev-dependencies]
tempfile = "3.8"