[package]
name = "in-memory-checkpoint-holder"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
sui-types.workspace = true
tokio.workspace = true
