system_object: 0x6c2547cbbc38025cf3adac45f63cb0a8d12ecf777cdc75a4971612bf97fdf6af
staking_object: 0xbe46180321c30aab2f8b3501e24048377287fa708018a5b7c2792b35fe339ee3
exchange_objects: []
wallet_config:
  # Optional path to the wallet config file.
  path: ./config/wallet/testnet_sub_wallet/testnet_sub1_wallet.yaml
  # Sui environment to use.
  active_env: testnet
  # Optional override for the Sui address to use.
  # active_address: 0x0000000000000000000000000000000000000000000000000000000000000000
rpc_urls:
  - https://fullnode.testnet.sui.io:443
communication_config:
  max_concurrent_writes: 2000
  max_concurrent_sliver_reads: 2000
  max_concurrent_metadata_reads: 2000
  max_concurrent_status_reads: 2000
  max_data_in_flight: 10737418240
