# Configuration for walrus-sui-archival.
context: mainnet
client_config_path: /opt/walrus/config/mainnet_client_config.yaml
db_path: /opt/walrus/data/db
thread_pool_size: 16
rest_api_address: "0.0.0.0:9185"
metrics_address: "0.0.0.0:9184"
# checkpoint_downloader:
#   type: bucket
#   bucket_base_url: "https://checkpoints.testnet.sui.io"
#   num_workers: 14
#   downloaded_checkpoint_dir: /opt/walrus/data/downloaded_checkpoints
checkpoint_downloader:
  type: injection_service
  remote_store_url: "https://checkpoints.mainnet.sui.io"
  num_workers: 50
  downloaded_checkpoint_dir: /opt/walrus/data/downloaded_checkpoints
  ingestion_config:
    checkpoint_buffer_size: 2000
    ingest_concurrency: 50
    retry_interval_ms: 1000
checkpoint_monitor:
  max_accumulation_duration: 1h
  max_accumulation_size_bytes: 3221225472 #3GB
checkpoint_blob_publisher:
  store_epoch_length: 7
  checkpoint_blobs_dir: /opt/walrus/data/checkpoint_blobs
  create_shared_blobs: true
checkpoint_blob_extender:
  check_interval: 24h
  extend_epoch_length: 5
archival_state_snapshot:
  snapshot_state_to_walrus_interval: 12h
  snapshot_temp_dir: /opt/walrus/data/archival_snapshots
  contract_package_id: 0x88fe0bdce11ce0c0a8fc37b2e9682e21d05051cd31522ac88dcff3076c051dc6
  wal_token_package_id: 0x356a26eb9e012a68958082340d4c4116e7f55615cf27affcff209cf0ae544f59
  admin_cap_object_id: 0x89cb23d8c8baa0a9813d50a7c17c6333dc4d22b720336d73fa761de72b9bdcc1
  metadata_pointer_object_id: 0xcdecb54e0e10e38cb2f6f69c7fdb05a5a899db3f77ff9de959b403b39f13e1c0
  metadata_pointer_initial_shared_version: 662168303
  store_epoch_length: 2
