# Configuration for walrus-sui-archival.
context: testnet
client_config_path: ./config/local_testnet_client_config.yaml
uploader_client_config_path:
  - ./config/local_testnet_client_config_sub1.yaml
  - ./config/local_testnet_client_config_sub2.yaml
thread_pool_size: 8
rest_api_address: "0.0.0.0:9185"
metrics_address: "0.0.0.0:9184"
# checkpoint_downloader:
#   type: bucket
#   bucket_base_url: "https://checkpoints.testnet.sui.io"
#   downloaded_checkpoint_dir: "downloaded_checkpoint_dir"
checkpoint_downloader:
  type: ingestion_service
  remote_store_url: "https://checkpoints.testnet.sui.io"
  downloaded_checkpoint_dir: "downloaded_checkpoint_dir"
  ingestion_config:
    checkpoint_buffer_size: 100
    ingest_concurrency: 20
    retry_interval_ms: 1000
checkpoint_blob_publisher:
  store_epoch_length: 2
  create_shared_blobs: true
checkpoint_blob_extender:
  check_interval: 60s
  extend_epoch_length: 2
archival_state_snapshot:
  snapshot_state_to_walrus_interval: 600s
  #snapshot_temp_dir:
  contract_package_id: 0x5066f4e1c7ec56acb4df4f53c7a0ebb0aab06fb161593c6ea4ed8e4b7f91246c
  wal_token_package_id: 0x8270feb7375eee355e64fdb69c50abb6b5f9393a722883c1cf45f8e26048810a
  admin_cap_object_id: 0x3c6aaedc4abf4e3acb218813a749199d54567a2acdda91e789b07d0664e8e454
  metadata_pointer_object_id: 0x6d0d5f76151e96e0f7cbad41c256c908bdbbcafdda48e0bd2880c216a5bbdbfe
  metadata_pointer_initial_shared_version: 621454879
  store_epoch_length: 2
