# Configuration for walrus-sui-archival.
context: testnet
client_config_path: /opt/walrus/config/testnet_client_config.yaml
db_path: /opt/walrus/data/db
thread_pool_size: 16
rest_api_address: "0.0.0.0:9185"
metrics_address: "0.0.0.0:9184"
# checkpoint_downloader:
#   type: bucket
#   bucket_base_url: "https://checkpoints.testnet.sui.io"
#   num_workers: 14
#   downloaded_checkpoint_dir: /opt/walrus/data/downloaded_checkpoints
checkpoint_downloader:
  type: injection_service
  remote_store_url: "https://checkpoints.testnet.sui.io"
  num_workers: 20
  downloaded_checkpoint_dir: /opt/walrus/data/downloaded_checkpoints
  ingestion_config:
    checkpoint_buffer_size: 1000
    ingest_concurrency: 20
    retry_interval_ms: 1000
checkpoint_monitor:
  max_accumulation_duration: 1h
  max_accumulation_size_bytes: 3221225472 #3GB
checkpoint_blob_publisher:
  store_epoch_length: 2
  checkpoint_blobs_dir: /opt/walrus/data/checkpoint_blobs
checkpoint_blob_extender:
  check_interval: 3600s
  extend_epoch_length: 2
archival_state_snapshot:
  snapshot_state_to_walrus_interval: 12h
  snapshot_temp_dir: /opt/walrus/data/archival_snapshots
  contract_package_id: 0x16b852d7c1d55de8ad64c9ae8384c8707482680f14cf827f026a5b98b309ab81
  wal_token_package_id: 0x8270feb7375eee355e64fdb69c50abb6b5f9393a722883c1cf45f8e26048810a
  admin_cap_object_id: 0x4223b0e2851c38df603c6ba90a60e363292bdc5ac56d148db44bf6c43bc4bd62
  metadata_pointer_object_id: 0x559d73e6c017af8ec77f5945e916664fb86b5141229036568a914ebe199e40c4
  metadata_pointer_initial_shared_version: 599718274
  store_epoch_length: 2
