# Configuration for walrus-sui-archival.
client_config_path: /opt/walrus/config/wallet/client_config.yaml
db_path: /opt/walrus/data/db
thread_pool_size: 16
rest_api_address: "0.0.0.0:9185"
metrics_address: "0.0.0.0:9186"
checkpoint_downloader:
  bucket_base_url: "https://checkpoints.testnet.sui.io"
  num_workers: 14
  downloaded_checkpoint_dir: /opt/walrus/data/downloaded_checkpoints
checkpoint_monitor:
  max_accumulation_duration: 1h
  max_accumulation_size_bytes: 3GB
checkpoint_blob_publisher:
  store_epoch_length: 2
  checkpoint_blobs_dir: /opt/walrus/data/checkpoint_blobs
checkpoint_blob_extender:
  check_interval: 3600s
  extend_epoch_length: 2
