# Configuration for walrus-sui-archival.
context: testnet
client_config_path: /opt/walrus/config/testnet_client_config.yaml
db_path: /opt/walrus/data/db
thread_pool_size: 16
rest_api_address: "0.0.0.0:9185"
metrics_address: "0.0.0.0:9184"
# checkpoint_downloader:
#   type: bucket
#   bucket_base_url: "https://checkpoints.testnet.sui.io"
#   num_workers: 14
#   downloaded_checkpoint_dir: /opt/walrus/data/downloaded_checkpoints
checkpoint_downloader:
  type: injection_service
  remote_store_url: "https://checkpoints.testnet.sui.io"
  num_workers: 20
  downloaded_checkpoint_dir: /opt/walrus/data/downloaded_checkpoints
  ingestion_config:
    checkpoint_buffer_size: 1000
    ingest_concurrency: 20
    retry_interval_ms: 1000
checkpoint_monitor:
  max_accumulation_duration: 1h
  max_accumulation_size_bytes: 3221225472 #3GB
checkpoint_blob_publisher:
  store_epoch_length: 2
  checkpoint_blobs_dir: /opt/walrus/data/checkpoint_blobs
checkpoint_blob_extender:
  check_interval: 3600s
  extend_epoch_length: 2
archival_state_snapshot:
  snapshot_state_to_walrus_interval: 12h
  snapshot_temp_dir: /opt/walrus/data/archival_snapshots
  contract_package_id: 0x32b66df04eb2deb6151b41e2f682457ae5288372997ce04f883a22aa50418416
  wal_token_package_id: 0x8270feb7375eee355e64fdb69c50abb6b5f9393a722883c1cf45f8e26048810a
  admin_cap_object_id: 0xcc32bca08130042b3a76ab174b66e030eff2238f7dd95306bc102aed94d84d44
  metadata_pointer_object_id: 0x3a191d073cd9226bf1743570910b67d3b87bb3610c2231ed0f2ecba3242635bd
  metadata_pointer_initial_shared_version: 599254701
  store_epoch_length: 2
