# Configuration for walrus-sui-archival.

client_config_path: ./config/local_client_config.yaml

# Total number of threads for the tokio runtime thread pool.
thread_pool_size: 8

# REST API server address.
# Default: 0.0.0.0:9185
rest_api_address: "0.0.0.0:9185"

# Metrics server address.
# Default: 0.0.0.0:9184
metrics_address: "0.0.0.0:9184"

# Configuration for the checkpoint downloader.
checkpoint_downloader:
  # Base URL for the S3 bucket containing checkpoints.
  bucket_base_url: "https://checkpoints.testnet.sui.io"

  # Directory to store downloaded checkpoint data.
  # If not specified, defaults to "downloaded_checkpoint_dir"
  downloaded_checkpoint_dir: "downloaded_checkpoint_dir"

checkpoint_blob_publisher:
  store_epoch_length: 1

checkpoint_blob_extender:
  check_interval: 60s
