# Configuration for walrus-sui-archival.
context: testnet
client_config_path: /opt/walrus/config/testnet_client_config.yaml
db_path: /opt/walrus/data/db
thread_pool_size: 16
rest_api_address: "0.0.0.0:9185"
metrics_address: "0.0.0.0:9184"
# checkpoint_downloader:
#   type: bucket
#   bucket_base_url: "https://checkpoints.testnet.sui.io"
#   num_workers: 14
#   downloaded_checkpoint_dir: /opt/walrus/data/downloaded_checkpoints
checkpoint_downloader:
  type: injection_service
  remote_store_url: "https://checkpoints.testnet.sui.io"
  num_workers: 50
  downloaded_checkpoint_dir: /opt/walrus/data/downloaded_checkpoints
  ingestion_config:
    checkpoint_buffer_size: 100
    ingest_concurrency: 50
    retry_interval_ms: 1000
checkpoint_monitor:
  max_accumulation_duration: 1h
  max_accumulation_size_bytes: 3221225472 #3GB
checkpoint_blob_publisher:
  store_epoch_length: 2
  checkpoint_blobs_dir: /opt/walrus/data/checkpoint_blobs
  create_shared_blobs: true
checkpoint_blob_extender:
  check_interval: 3600s
  extend_epoch_length: 2
archival_state_snapshot:
  snapshot_state_to_walrus_interval: 12h
  snapshot_temp_dir: /opt/walrus/data/archival_snapshots
  contract_package_id: 0xab933040652f54d198b2f73f3ca8d3ac0d65e5146a8e7911a7a7fb5aa992fa56
  wal_token_package_id: 0x8270feb7375eee355e64fdb69c50abb6b5f9393a722883c1cf45f8e26048810a
  admin_cap_object_id: 0x23e6025b4f45147d6d817cf82801f7fc082ad0fb12792c850e4b9ab536c2a5b2
  metadata_pointer_object_id: 0xaf35f2fc9ec13a625ddced86e980e7983f49eff3cbbf65cbc4e890e654937283
  metadata_pointer_initial_shared_version: 599718276
  store_epoch_length: 2
